areainfo = [{'moves':10,'loc':'Garden'},{'moves':31,'loc':'Garden'},
            {'moves':15,'loc':'Garden'},
            {'moves':18,'loc':'Garden'},
            {'moves':52,'loc':'Garden'},
            {'moves':73,'loc':'Garden'},
            {'moves':314,'loc':'Garden'},
            {'moves':103,'loc':'Garden'},
            {'moves':48,'loc':'Desert'},
            {'moves':28,'loc':'Desert'},
            {'moves':77,'loc':'Desert'},
            {'moves':28,'loc':'Desert'},
            {'moves':47,'loc':'Desert'},
            {'moves':44,'loc':'Desert'},
            {'moves':113,'loc':'Desert'},
            {'moves':28,'loc':'Desert'},
            {'moves':69,'loc':'Desert'},
            {'moves':145,'loc':'Foreston'},
            {'moves':68,'loc':'Forest Woods'},
            {'moves':57,'loc':'Forest Woods'},
            {'moves':98,'loc':'Forest Woods'},
            {'moves':73,'loc':'Forest Woods'},
            {'moves':85,'loc':'Forest Woods'},
            {'moves':133,'loc':'Forest Woods'},
            {'moves':103,'loc':'Forest Woods'},
            {'moves':40,'loc':'Forest Woods'},
            {'moves':137,'loc':'Forest Woods'},
            {'moves':46,'loc':'Forest Woods'},
            {'moves':533,'loc':'Forest Woods'},
            {'moves':82,'loc':'Forest Woods'},
            {'moves':10,'loc':'Garden'},
            {'moves':71,'loc':'Garden'},
            {'moves':31,'loc':'Garden'},
            {'moves':26,'loc':'Garden'},
            {'moves':77,'loc':'Garden'},
            {'moves':18,'loc':'Forest Woods'},
            {'moves':28,'loc':'Forest Woods'},
            {'moves':20,'loc':'Forest Woods'},
            {'moves':25,'loc':'Forest Woods'},
            {'moves':10,'loc':'Winter Island'},
            {'moves':22,'loc':'Winter Island'},
            {'moves':22,'loc':'Winter Island'},
            {'moves':20,'loc':'Winter Island'},
            {'moves':42,'loc':'Winter Island'},
            {'moves':42,'loc':'Winter Island'},
            {'moves':10,'loc':'Winter Island'},
            {'moves':19,'loc':'Winter Island'},
            {'moves':64,'loc':'Winter Island'},
            {'moves':14,'loc':'Winter Island'},
            {'moves':37,'loc':'Winter Island'},
            {'moves':65,'loc':'Winter Island'},
            {'moves':104,'loc':'Winter Island'},
            {'moves':65,'loc':'Winter Island'},
            {'moves':53,'loc':'Winter Island'},
            {'moves':85,'loc':'Winter Island'},
            {'moves':32,'loc':'Winter Island'},
            {'moves':86,'loc':'Winter Island'},
            {'moves':145,'loc':'Winter Island'},
            {'moves':143,'loc':'Winter Island'},
            {'moves':102,'loc':'Winter Island'},
            {'moves':259,'loc':'Winter Island'},
            {'moves':11,'loc':'Autumn Island'},
            {'moves':25,'loc':'Autumn Island'},
            {'moves':43,'loc':'Autumn Island'},
            {'moves':45,'loc':'Autumn Island'},
            {'moves':55,'loc':'Autumn Island'},
            {'moves':11,'loc':'Autumn Island'},
            {'moves':11,'loc':'Autumn Island'},
            {'moves':61,'loc':'Autumn Island'},
            {'moves':16,'loc':'Autumn Island'},
            {'moves':28,'loc':'Autumn Island'},
            {'moves':47,'loc':'Autumn Island Underground'},
            {'moves':33,'loc':'Autumn Island Underground'},
            {'moves':46,'loc':'Autumn Island Underground'},
            {'moves':74,'loc':'Autumn Island Underground'},
            {'moves':77,'loc':'Autumn Island Underground'},
            {'moves':86,'loc':'Autumn Island Underground'},
            {'moves':330,'loc':'Autumn Island Underground'},
            {'moves':382,'loc':'Autumn Island Underground'},
            {'moves':38,'loc':'Autumn Island Underground'},
            {'moves':84,'loc':'Autumn Island Underground'},
            {'moves':274,'loc':'Autumn Island'},
            {'moves':55,'loc':'Autumn Island House'},
            {'moves':295,'loc':'Autumn Island'},
            {'moves':46,'loc':'Autumn Island'},
            {'moves':195,'loc':'Autumn Island'},
            {'moves':0,'loc':'Autumn Island'},
            {'moves':31,'loc':'Autumn Island Underground'},
            {'moves':25,'loc':'Autumn Island Underground'},
            {'moves':205,'loc':'Autumn Island'},
            {'moves':65,'loc':'Desert'},
            {'moves':39,'loc':'Desert'},
            {'moves':0,'loc':'Desert'},
            {'moves':122,'loc':'Desert'},
            {'moves':45,'loc':'Desert'},
            {'moves':40,'loc':'Tower Basement'},
            {'moves':60,'loc':'Tower Basement'},
            {'moves':232,'loc':'Tower Basement'},
            {'moves':145,'loc':'Tower Basement'},
            {'moves':999,'loc':'Tower Basement'},
            {'moves':80,'loc':'Tower Basement'},
            {'moves':160,'loc':'Tower Basement'},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':'Autumn Island Underground'},
            {'moves':0,'loc':'Autumn Island Underground'},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''},
            {'moves':0,'loc':''}]
